import type { Metadata } from "next";
import localFont from "next/font/local";
import ModalsWrapper from "@/providers/ModalsWrapper";
import { ApolloWrapper } from "@/apollo/ApolloWrapper";
import "./globals.css";

const nexaFont = localFont({
  src: [
    {
      path: "../fonts/Nexa-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/Nexa-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/Nexa-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/Nexa-XBold.otf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-nexa",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nexaFont.variable} font-nexa font-normal antialiased`}
      >
        <ApolloWrapper>
          <ModalsWrapper />
          {children}
        </ApolloWrapper>
      </body>
    </html>
  );
}
